config/routes.rb
SelectionManager::Application.routes.draw do
  resources :selections

  devise_for :users

  resources :enterprises

end

app/models/enterprise.rb
class Enterprise < ActiveRecord::Base
  attr_accessible :cnpj, :name
  has_many :selections
end

app/models/selection.rb
class Selection < ActiveRecord::Base
  attr_accessible :description, :title, :enterprise_id
  belongs_to :enterprise
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/enterprises_controller.rb
class EnterprisesController < ApplicationController
  # GET /enterprises
  # GET /enterprises.json
  #before_filter :authenticate_user!
  def index
    @enterprises = Enterprise.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @enterprises }
    end
  end

  # GET /enterprises/1
  # GET /enterprises/1.json
  def show
    @enterprise = Enterprise.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @enterprise }
    end
  end

  # GET /enterprises/new
  # GET /enterprises/new.json
  def new
    @enterprise = Enterprise.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @enterprise }
    end
  end

  # GET /enterprises/1/edit
  def edit
    @enterprise = Enterprise.find(params[:id])
  end

  # POST /enterprises
  # POST /enterprises.json
  def create
    @enterprise = Enterprise.new(params[:enterprise])

    respond_to do |format|
      if @enterprise.save
        format.html { redirect_to @enterprise, notice: 'Enterprise was successfully created.' }
        format.json { render json: @enterprise, status: :created, location: @enterprise }
      else
        format.html { render action: "new" }
        format.json { render json: @enterprise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /enterprises/1
  # PUT /enterprises/1.json
  def update
    @enterprise = Enterprise.find(params[:id])

    respond_to do |format|
      if @enterprise.update_attributes(params[:enterprise])
        format.html { redirect_to @enterprise, notice: 'Enterprise was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @enterprise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enterprises/1
  # DELETE /enterprises/1.json
  def destroy
    @enterprise = Enterprise.find(params[:id])
    @enterprise.destroy

    respond_to do |format|
      format.html { redirect_to enterprises_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  # GET /selections
  # GET /selections.json
  def index
    @selections = Selection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @selections }
    end
  end

  # GET /selections/1
  # GET /selections/1.json
  def show
    @selection = Selection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @selection }
    end
  end

  # GET /selections/new
  # GET /selections/new.json
  def new
    @selection = Selection.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @selection }
    end
  end

  # GET /selections/1/edit
  def edit
    @selection = Selection.find(params[:id])
  end

  # POST /selections
  # POST /selections.json
  def create
    @selection = Selection.new(params[:selection])

    respond_to do |format|
      if @selection.save
        format.html { redirect_to @selection, notice: 'Selection was successfully created.' }
        format.json { render json: @selection, status: :created, location: @selection }
      else
        format.html { render action: "new" }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /selections/1
  # PUT /selections/1.json
  def update
    @selection = Selection.find(params[:id])

    respond_to do |format|
      if @selection.update_attributes(params[:selection])
        format.html { redirect_to @selection, notice: 'Selection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selections/1
  # DELETE /selections/1.json
  def destroy
    @selection = Selection.find(params[:id])
    @selection.destroy

    respond_to do |format|
      format.html { redirect_to selections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enterprises_helper.rb
module EnterprisesHelper
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/views/enterprises/_form.html.erb
<%= form_for(@enterprise) do |f| %>
  <% if @enterprise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enterprise.errors.count, "error") %> prohibited this enterprise from being saved:</h2>

      <ul>
      <% @enterprise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br />
    <%= f.text_field :cnpj %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enterprises/edit.html.erb
<h1>Editing enterprise</h1>

<%= render 'form' %>

<%= link_to 'Show', @enterprise %> |
<%= link_to 'Back', enterprises_path %>

app/views/enterprises/index.html.erb
<h1>Listing enterprises</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Cnpj</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @enterprises.each do |enterprise| %>
  <tr>
    <td><%= enterprise.name %></td>
    <td><%= enterprise.cnpj %></td>
    <td><%= link_to 'Show', enterprise %></td>
    <td><%= link_to 'Edit', edit_enterprise_path(enterprise) %></td>
    <td><%= link_to 'Destroy', enterprise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Criar Nova seleção' , new_selection_path(:id => enterprise.id) %> </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enterprise', new_enterprise_path %>

app/views/enterprises/new.html.erb
<h1>New enterprise</h1>

<%= render 'form' %>

<%= link_to 'Back', enterprises_path %>

app/views/enterprises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @enterprise.name %>
</p>

<p>
  <b>Cnpj:</b>
  <%= @enterprise.cnpj %>
</p>


<%= link_to 'Edit', edit_enterprise_path(@enterprise) %> |
<%= link_to 'Back', enterprises_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SelectionManager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
   Signed in as <%=current_user.email %>. Not you? 
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
  <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/selections/_form.html.erb
<%= form_for(@selection) do |f| %>
  <% if @selection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@selection.errors.count, "error") %> prohibited this selection from being saved:</h2>

      <ul>
      <% @selection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
  
  </div>
  <div class="field">

    <%= f.label :desciption %><br />
    <%= f.text_area :desciption %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/selections/edit.html.erb
<h1>Editing selection</h1>

<%= render 'form' %>

<%= link_to 'Show', @selection %> |
<%= link_to 'Back', selections_path %>

app/views/selections/index.html.erb
<h1>Listing selections</h1>

<table>
  <tr>
    <th>Desciption</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @selections.each do |selection| %>
  <tr>
    <td><%= selection.desciption %></td>
    <td><%= selection.title %></td>
    <td><%= link_to 'Show', selection %></td>
    <td><%= link_to 'Edit', edit_selection_path(selection) %></td>
    <td><%= link_to 'Destroy', selection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Selection', new_selection_path %>

app/views/selections/new.html.erb
<h1>New selection</h1>

<%= render 'form' %>

<%= link_to 'Back', selections_path %>

app/views/selections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Desciption:</b>
  <%= @selection.desciption %>
</p>

<p>
  <b>Title:</b>
  <%= @selection.title %>
</p>


<%= link_to 'Edit', edit_selection_path(@selection) %> |
<%= link_to 'Back', selections_path %>